version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: franckfesse/directory
    volumes:
      - static_volume:/home/directory/static
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    networks:
      - redis_network
      - db_network
    env_file:
      - ./.env
  redis:
    image: redis:latest
    networks:
      - redis_network
    volumes:
      - redis_data:/data


networks:
  redis_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  static_volume:
  directory: