version: "3.3"

services:
  web:
    build: .
    command: bash -c "cd directory && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/home/directory/static
      - .:/code
    ports:
      - "8000:8000"      
    depends_on:
      - redis
    networks:
      - redis_network
    env_file:
      - ./.env  
  redis:
    image: redis:latest
    networks:
      - redis_network
    volumes:
      - redis_data:/data
  

networks:
  redis_network:
    driver: bridge

volumes:
  redis_data:
  static_volume:
  directory: