# Generated by Django 3.0.8 on 2020-10-06 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='mailinglist name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('mailinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.MailingList')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('mailinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.MailingList')),
            ],
            options={
                'unique_together': {('email', 'mailinglist')},
            },
        ),
    ]
