version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network
    env_file:
      - ./.env 
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - static:/static
    ports:
      - "8000:8000"      
    depends_on:
      - db
      - redis
    networks:
      - db_network
      - redis_network
    env_file:
      - ./.env  
  redis:
    image: redis:latest
    networks:
      - redis_network
    volumes:
      - redis_data:/data
  

networks:
  db_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  static:
