version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network      
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: "gunicorn --bind 0.0.0.0:8000 directory.wsgi"
    volumes:
      - .:/code
      - static:/static  
    expose:
      - 8000
    depends_on:
      - db
      - redis
    networks:
      - db_network
      - redis_network      
  redis:
    image: redis:latest
    networks:
      - redis_network
    volumes:
      - redis_data:/data      
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

networks:
  db_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:        
  static:
  db_data:
