# Generated by Django 3.0.8 on 2020-07-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook_page',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin_page',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='postal_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter_page',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
