# Generated by Django 3.0.8 on 2022-03-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220228_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='house_name',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
