# Generated by Django 3.0.8 on 2020-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200721_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('PLC', 'public limited company'), ('LTD', 'private limited company'), ('STD', 'sole trader')], default='PLC', max_length=200),
        ),
    ]
