# Generated by Django 3.0.8 on 2020-08-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200728_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dissolved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
