# Generated by Django 3.0.8 on 2020-08-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200806_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='categories',
            field=models.ManyToManyField(related_name='companies', to='core.Category'),
        ),
    ]
