# Generated by Django 3.0.8 on 2020-09-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200901_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='media/logo/default_logo.png', upload_to='logo/'),
        ),
    ]
