# Generated by Django 3.0.8 on 2020-09-21 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_auto_20200919_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='followers',
            field=models.ManyToManyField(related_name='companies', through='core.Follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('category_linked', models.ManyToManyField(blank=True, null=True, to='core.Category')),
                ('company_linked', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
        ),
    ]
